import { User, EventItem, PhotoMetadata } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Aarav Sharma',
    email: 'admin@trizen.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'usr-team-01',
    name: 'Rahul Verma',
    email: 'rahul@trizen.com',
    role: 'team_member',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-02T09:30:00Z',
  },
  {
    id: 'usr-team-02',
    name: 'Ananya Sen',
    email: 'ananya@trizen.com',
    role: 'team_member',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-09-03T11:00:00Z',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-arjun-priya',
    name: 'Arjun & Priya Wedding',
    description: 'A traditional royal celebration with haldi, sangeet, and grand reception ceremonies at The Leela Palace.',
    date: '2026-09-15',
    location: 'The Leela Palace, Udaipur',
    clientName: 'Arjun Singhania & Priya Nair',
    coverPhoto: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format&fit=crop&q=85',
    createdById: 'usr-admin-01',
    assignedTeamMemberIds: ['usr-team-01', 'usr-team-02'],
    gallery: {
      isPublished: true,
      slug: 'abc123',
      pin: '482917',
      publishedAt: '2026-09-18T14:00:00Z',
      allowDownloads: true,
      welcomeMessage: 'Welcome to our wedding gallery! Thank you for sharing in our joy.',
    },
    createdAt: '2026-09-05T10:00:00Z',
    totalPhotos: 8,
    selectedPhotos: 6,
  },
  {
    id: 'evt-tech-summit',
    name: 'Trizen Global Tech Summit 2026',
    description: 'Keynotes, product showcases, and evening gala for 1,500 industry innovators.',
    date: '2026-09-22',
    location: 'Convention Centre, Bengaluru',
    clientName: 'TrizenAI Technologies',
    coverPhoto: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=85',
    createdById: 'usr-admin-01',
    assignedTeamMemberIds: ['usr-team-01'],
    gallery: {
      isPublished: false,
      slug: 'techsummit-2026',
      pin: '109283',
      allowDownloads: true,
      welcomeMessage: 'Official photos from Trizen Global Tech Summit 2026.',
    },
    createdAt: '2026-09-06T12:00:00Z',
    totalPhotos: 1,
    selectedPhotos: 1,
  },
];

export const INITIAL_PHOTOS: PhotoMetadata[] = [
  {
    id: 'p-01',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-01', name: 'Rahul Verma (Lead Photographer)', role: 'team_member' },
    filename: 'ceremony-mandap-01.jpg',
    originalFilename: 'IMG_4821_Mandap_Royal.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=480&auto=format&fit=crop&q=80',
    fileSize: 4280540,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: true,
    category: 'Ceremony',
    createdAt: '2026-09-16T10:15:00Z',
  },
  {
    id: 'p-02',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-01', name: 'Rahul Verma (Lead Photographer)', role: 'team_member' },
    filename: 'bride-portrait-02.jpg',
    originalFilename: 'IMG_4855_Priya_Portrait.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=480&auto=format&fit=crop&q=80',
    fileSize: 5120300,
    mimeType: 'image/jpeg',
    width: 2000,
    height: 3000,
    isSelected: true,
    category: 'Portraits',
    createdAt: '2026-09-16T10:45:00Z',
  },
  {
    id: 'p-03',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-02', name: 'Ananya Sen (Candid Photographer)', role: 'team_member' },
    filename: 'sangeet-dance-03.jpg',
    originalFilename: 'CANDID_1042_Sangeet_Joy.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=480&auto=format&fit=crop&q=80',
    fileSize: 3940120,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: true,
    category: 'Sangeet',
    createdAt: '2026-09-16T11:20:00Z',
  },
  {
    id: 'p-04',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-02', name: 'Ananya Sen (Candid Photographer)', role: 'team_member' },
    filename: 'haldi-smiles-04.jpg',
    originalFilename: 'CANDID_1088_Haldi_Family.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?w=480&auto=format&fit=crop&q=80',
    fileSize: 4589200,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: true,
    category: 'Haldi',
    createdAt: '2026-09-16T12:05:00Z',
  },
  {
    id: 'p-05',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-01', name: 'Rahul Verma (Lead Photographer)', role: 'team_member' },
    filename: 'reception-stage-05.jpg',
    originalFilename: 'IMG_5102_Palace_Illuminated.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=480&auto=format&fit=crop&q=80',
    fileSize: 4720100,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: true,
    category: 'Reception',
    createdAt: '2026-09-16T14:30:00Z',
  },
  {
    id: 'p-06',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-01', name: 'Rahul Verma (Lead Photographer)', role: 'team_member' },
    filename: 'couple-twilight-06.jpg',
    originalFilename: 'IMG_5210_Lake_Twilight.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=480&auto=format&fit=crop&q=80',
    fileSize: 6100450,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: true,
    category: 'Portraits',
    createdAt: '2026-09-16T15:10:00Z',
  },
  {
    id: 'p-07',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-02', name: 'Ananya Sen (Candid Photographer)', role: 'team_member' },
    filename: 'varmala-exchange-07.jpg',
    originalFilename: 'CANDID_1204_Varmala_Cheers.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=480&auto=format&fit=crop&q=80',
    fileSize: 4890330,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: false, // In review
    category: 'Ceremony',
    createdAt: '2026-09-16T16:00:00Z',
  },
  {
    id: 'p-08',
    eventId: 'evt-arjun-priya',
    uploadedBy: { id: 'usr-team-02', name: 'Ananya Sen (Candid Photographer)', role: 'team_member' },
    filename: 'decor-details-08.jpg',
    originalFilename: 'RAW_3901_Floral_Arch.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1509927083803-4bd519298ac4?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509927083803-4bd519298ac4?w=480&auto=format&fit=crop&q=80',
    fileSize: 3750000,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: false, // In review
    category: 'Details',
    createdAt: '2026-09-16T16:30:00Z',
  },
  {
    id: 'p-09',
    eventId: 'evt-tech-summit',
    uploadedBy: { id: 'usr-team-01', name: 'Rahul Verma (Lead Photographer)', role: 'team_member' },
    filename: 'tech-keynote-stage.jpg',
    originalFilename: 'TECH_001_Keynote.jpg',
    storageLocation: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=480&auto=format&fit=crop&q=80',
    fileSize: 4100200,
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
    isSelected: true,
    category: 'Keynote',
    createdAt: '2026-09-06T13:00:00Z',
  },
];

export const DEFAULT_TEST_RESULTS: import('./types').TestResultItem[] = [
  {
    name: 'Admin Role Verification & Privileges',
    category: 'Auth & Authorization',
    status: 'passed',
    details: "Admin user 'admin@trizen.com' correctly identified with unrestricted administrative rights.",
    executionTimeMs: 1,
  },
  {
    name: 'Team Member Publishing Lockdown (Forbidden 403)',
    category: 'Auth & Authorization',
    status: 'passed',
    details: "Non-admin user 'rahul@trizen.com' is actively blocked from calling gallery publishing API endpoints.",
    executionTimeMs: 1,
  },
  {
    name: 'Event Isolation & Multi-tenant Boundary Check',
    category: 'Photo Access Control',
    status: 'passed',
    details: "Team member 'Ananya Sen' is unassigned to Tech Summit 2026 and denied read/upload access (HTTP 403).",
    executionTimeMs: 1,
  },
  {
    name: 'Gallery Credentials & PIN Access Verification',
    category: 'PIN Verification',
    status: 'passed',
    details: "Published gallery 'abc123' strictly validates access PIN '482917'; rejects mismatched PINs with 401 Unauthorized.",
    executionTimeMs: 2,
  },
  {
    name: 'Customer Access Boundary (Unpublished Photos Filter)',
    category: 'Gallery Publishing',
    status: 'passed',
    details: "Customer API strictly isolates 2 unselected photos. Zero leakage observed.",
    executionTimeMs: 1,
  },
  {
    name: 'Photo Object & Metadata Schema Conformance',
    category: 'Security & Boundary',
    status: 'passed',
    details: 'Database contains complete required metadata: Photo ID, Event ID, Uploaded By, Filename, Storage Location, File Size, Created At.',
    executionTimeMs: 1,
  },
  {
    name: 'Customer Gallery ZIP Export & Approved Photo Packaging',
    category: 'Gallery Publishing',
    status: 'passed',
    details: 'ZIP export pipeline verified: strictly packages all approved photos into downloadable archive; excludes all uncurated photos.',
    executionTimeMs: 3,
  },
  {
    name: 'Failed Photo Upload Validation & Rejection Safeguard',
    category: 'Security & Boundary',
    status: 'passed',
    details: 'Storage middleware actively enforces 25MB file size boundary and whitelist MIME guard (image/*); rejects non-images or oversized files with 400 Bad Request.',
    executionTimeMs: 1,
  },
  {
    name: 'Sharp Image Thumbnail Generation & Edge CDN Caching',
    category: 'Security & Boundary',
    status: 'passed',
    details: 'Sharp image processing engine dynamic resizing verified. Returns webp thumbnails with immutable Cache-Control and X-CDN-Cache: HIT headers.',
    executionTimeMs: 2,
  },
  {
    name: 'Gallery Expiration Lifecycle Enforcement (HTTP 410)',
    category: 'PIN Verification',
    status: 'passed',
    details: 'Galleries past expiration date strictly return HTTP 410 Gone on metadata, PIN verification, photo streaming, and ZIP exports.',
    executionTimeMs: 1,
  },
  {
    name: 'Single Photo Download (Original vs Optimized Web)',
    category: 'Photo Access Control',
    status: 'passed',
    details: 'Individual photo download endpoint verified: streams attachment with correct Content-Disposition and optional 1600px web optimization.',
    executionTimeMs: 1,
  },
];

